// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'bgContainer': string;
  'containerFluid': string;
  'fades-in-out': string;
}
declare var cssExports: CssExports;
export = cssExports;
