// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'defaultLink': string;
  'fades-in-out': string;
  'landingContent': string;
  'landingHeader': string;
  'logo': string;
  'navbarLinks': string;
  'primaryLink': string;
}
declare var cssExports: CssExports;
export = cssExports;
